function(check_input name input expected_result expected_text)
    set(input_path "${TEST_DIR}/${name}.txt")
    file(WRITE "${input_path}" "${input}")
    execute_process(COMMAND "${ATOM_SIM}" --console
        INPUT_FILE "${input_path}" WORKING_DIRECTORY "${SOURCE_DIR}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 10)
    if(NOT "${result}" STREQUAL "${expected_result}")
        message(FATAL_ERROR "${name}: exit ${result}; ${output}${error}")
    endif()
    string(FIND "${output}${error}" "${expected_text}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "${name}: missing '${expected_text}'; ${output}${error}")
    endif()
endfunction()
check_input(decimal_m "H\n2p\n1.5\ns\n" 1 "m must be a whole integer")
check_input(overflow_m "H\n2p\n99999999999999999\np\n" 1 "m must be a whole integer")
check_input(out_of_range_m "H\n2p\n-2\np\n" 1 "m must be a whole integer")
check_input(trailing_Z "26abc\n1s\np\n" 1 "Atomic number must be a whole integer")
check_input(trailing_orbital "H\n2pabc\n0\np\n" 1 "Invalid orbital")
check_input(invalid_custom_Z "X\n2.5\n" 1 "Custom Z must be a positive whole integer")
check_input(invalid_choice "H\n1s\nperhaps\n" 1 "Screening choice must be p or s")
check_input(eof "H\n" 1 "Input ended before setup was complete")
check_input(valid_m "H\n2p\n+1\np\n" 0 "n=2, l=1, m=1")
check_input(gold "Au\n6s\ns\n" 0 "Z_eff           : 3.700000")
execute_process(COMMAND "${ATOM_SIM}" --console --visual RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 1 OR NOT error MATCHES "Choose either")
    message(FATAL_ERROR "Conflicting modes were not rejected")
endif()
execute_process(COMMAND "${ATOM_SIM}" --bogus RESULT_VARIABLE result ERROR_VARIABLE error)
if(NOT result EQUAL 1 OR NOT error MATCHES "Unknown option")
    message(FATAL_ERROR "Unknown argument was not rejected")
endif()
